local test = require('main')

test.describe('@lutes/test', function (it, expect)
    it('should have defined methods it, expect, and describe', function()
        expect(test.expect).toBeDefined()
        expect(test.it).toBeDefined()
        expect(test.expect).toBeType('function')
        expect(test.it).toBeType('function')
        expect(test.describe).toBeType('function')
    end)
end)

test.describe('@lutes/describe', function (it, expect)
    it('should pass it and expect to the callback function', function ()
        expect(expect).toBeType('function')
        expect(it).toBeType('function')
    end)

    it('should fail', function()
        expect(0).toBe(1)
    end)
end)

test.describe('@lutes/expect', function(it, expect)
    it('should be defined', function()
        expect(1).toBeDefined()
    end)
    it('should be undefined', function ()
        expect(nil).toBeUndefined()
    end)
    it('should handle length', function()
        expect('123').toHaveLength(3)
        expect({1,2,3}).toHaveLength(3)
    end)
    it('should fail length', function()
        expect('123').toHaveLength(2)
        expect({1,2,3}).toHaveLength(2)
    end)

    it('should handle contains', function()
        expect('123').toContain('2')
        expect({1,2,3}).toContain(2)
    end)
    it('should fail contains',  function ()
        expect('123').toContain('1234')
        expect({1,2,3}).toContain('1')
    end)
end)

